In [7]:
import wandb

api = wandb.Api()
artifact = api.artifact('makkuror/fed_train19/best_eval_accuracy:v6', type='model')

In [8]:
artifact.download()

wandb:   1 of 1 files downloaded.  


'.\\artifacts\\best_eval_accuracy-v6'

In [1]:
from copy import deepcopy
from dataclasses import dataclass
import multiprocessing as mp
from re import T
import torchvision.models as models
import torch
import copy
import torch.nn.functional as F
#from model import net
import random
import multiprocessing as mp
import os
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
from torchvision import datasets,transforms
import random
from torch import optim,ceil
import torch.nn.functional as F
from torch import nn
import pickle
import numpy as np
import os
import pandas as pd
from torchvision.io import read_image
from torch.utils.data import Dataset,DataLoader
from torchvision import transforms
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
from pandas import DataFrame

In [2]:
model=models.mobilenet_v2(pretrained=True)
model.classifier[1]=(torch.nn.Linear(in_features=1280, out_features=6, bias=True))

In [3]:

from torch.utils.data import Dataset,DataLoader
import numpy as np

class plantdisease(Dataset):
    def __init__(self, df,
                  img_dir='data/oneFolder'
                 , isTest=False):
        self.img_labels=df
        self.img_dir='../../Data/DataResized512/'
       # self.train, self.test = train_test_split(self.img_labels, test_size=0.05)

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
            img_path = os.path.join(self.img_dir, self.img_labels['image'][idx])

            image = (read_image(img_path).float())
            self.transform=transforms.Compose([transforms.Resize((342,512)),
        transforms.Normalize((124.4455, 159.9584, 104.1832), (47.1528, 41.4626, 49.2424))])
            image = self.transform(image)
            label = self.img_labels['labels'][idx]
            label=np.fromstring(label[1:-1], dtype=np.int,sep=',')
            return image, label
df=pd.read_csv('../../Data/datafull.csv')
df: DataFrame=df.drop('Unnamed: 0',axis=1)
train,valid_test=train_test_split(df,test_size=0.2)
valid,test=train_test_split(valid_test,test_size=0.5)

train_data=plantdisease(df=train.reset_index())
dataloader=torch.utils.data.DataLoader(train_data,
                                    batch_size=int(8),
                                    shuffle=True)

In [4]:
def cfs_matrix_calculate(y,pred):
  pred=torch.sigmoid(pred)
  pred=torch.round(pred)
  
  
  matrix=0
  for i in range(0,y.shape[0]):
    matrix+=confusion_matrix(y[i], pred[i],labels=[1, 0])
  return matrix

In [15]:
tp=confusion_matri[0][0]
fp=confusion_matri[0][1]
fn=confusion_matri[1][0]
tn=confusion_matri[1][1]

accuracy=(tp+tn)/(fp+fn+tp+tn)

In [5]:
from sklearn.metrics import accuracy_score

In [11]:
tp

5

In [10]:
tn

23

In [16]:
accuracy

0.9583333333333334

In [ ]:
loss()

In [30]:
model.eval()
for x,y in dataloader:
    output=model(x)
    confusion_matri=(cfs_matrix_calculate(y,output.detach()))
    pred=torch.sigmoid(output)
    pred=torch.round(pred)
    print(accuracy_score(y.float(), pred.detach()))
    losss =torch.nn.BCEWithLogitsLoss()
    print(losss(y.float(),output))
    print(output)
    print(pred)
    print(y)
    break

C:\Users\nonom\AppData\Local\Temp\ipykernel_18864\2619517388.py:23: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  label=np.fromstring(label[1:-1], dtype=np.int,sep=',')


0.5
tensor(0.7656, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor([[-2.7768, -2.2075, -0.4722, -1.9882, -2.5763,  1.2437],
        [-0.3502,  0.3128, -2.4385, -2.5988, -1.9949, -1.8241],
        [-2.5217, -1.8001,  1.0637, -2.8473, -2.3326, -1.5185],
        [-1.7073, -2.0478, -0.9305, -2.5032, -1.2936,  0.6782],
        [-1.6584,  0.0698, -2.5726, -2.3363, -0.0156, -1.4907],
        [-1.7308,  0.2052, -0.9497, -2.1889, -2.8589, -0.6010],
        [ 0.1683,  2.0162, -3.5455, -2.5129, -1.9839, -2.2503],
        [-1.1214, -1.3774, -0.4834, -1.1184, -2.2659, -0.5476]],
       grad_fn=<AddmmBackward0>)
tensor([[0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], grad_fn=<RoundBackward0>)
tensor([[0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
   

In [12]:
model.load_state_dict(torch.load('./bestmodel.h5'))

<All keys matched successfully>

In [13]:
model

MobileNetV2(
  (features): Sequential(
    (0): ConvNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): ConvNormActivation(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): ConvNormActivation(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=1e-05,